version: '3.8'

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: WeatherETL
      POSTGRES_PASSWORD: WeatherETL
      POSTGRES_DB: WeatherETL
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-scheduler:
    build: ./docker  # Points to the folder containing your Dockerfile
    depends_on:
      - db
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://WeatherETL:WeatherETL@db:5432/WeatherETL
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags        # Simple relative path from root
      - ./scripts:/opt/airflow/scripts  # Simple relative path from root
    command: scheduler

  airflow-webserver:
    build: ./docker
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://WeatherETL:WeatherETL@db:5432/WeatherETL
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
    command: webserver

volumes:
  postgres_data: