version: '3.8'

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: WeatherETL
      POSTGRES_PASSWORD: WeatherETL
      POSTGRES_DB: WeatherETL
    ports:
      # Map host port 5435 to the default Postgres port 5432
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: